models/FormContact.php
<?php
namespace app\models;

use Yii;
use yii\base\Model;

class FormContact extends Model 
{
	public $fullname;
    public $email;
    public $message;

    public function rules()
    {
        return [
            [['fullname','email','message'], 'required'],
            ['email', 'email'],
			[['message'], 'string', 'max' => 300],
        ];
    }
}

models/FormRegister.php
<?php
namespace app\models;

use Yii;
use yii\base\Model;

class FormRegister extends Model 
{
	public $firstname;
    public $lastname;
    
    public $email;
    public $password;

    public function rules()
    {
        return [
            [['firstname','lastname','email','password'], 'required'],
            [['firstname'], 'string', 'max' => 15],
            [['lastname'], 'string', 'max' => 15],
            ['email', 'email'],
        ];
    }
}

models/JenisProduk.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "jenis_produk".
 *
 * @property integer $idjenisproduk
 * @property string $namaproduk
 * @property double $hargaproduk
 * @property string $kategori
 * @property string $gambar
 */
class JenisProduk extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'jenis_produk';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['namaproduk', 'hargaproduk', 'kategori', 'gambar'], 'required'],
            [['hargaproduk'], 'number'],
            [['kategori'], 'string'],
            [['namaproduk'], 'string', 'max' => 20],
            [['gambar'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'idjenisproduk' => 'Idjenisproduk',
            'namaproduk' => 'Namaproduk',
            'hargaproduk' => 'Hargaproduk',
            'kategori' => 'Kategori',
            'gambar' => 'Gambar',
        ];
    }
}

models/Messages.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "messages".
 *
 * @property integer $id
 * @property string $date_create
 * @property string $fullname
 * @property string $email
 * @property string $message
 */
class Messages extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'messages';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date_create'], 'safe'],
            [['fullname'], 'string', 'max' => 30],
            [['email'], 'string', 'max' => 50],
            [['message'], 'string', 'max' => 300],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date_create' => 'Date Create',
            'fullname' => 'Fullname',
            'email' => 'Email',
            'message' => 'Message',
        ];
    }
}

models/Usersign.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "usersign".
 *
 * @property integer $id
 * @property string $date_create
 * @property string $firstname
 * @property string $lastname
 * @property string $email
 * @property string $password
 * @property string $last_login
 */
class Usersign extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'usersign';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date_create', 'last_login'], 'safe'],
            [['firstname', 'lastname'], 'string', 'max' => 15],
            [['email'], 'string', 'max' => 50],
            [['password'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date_create' => 'Date Create',
            'firstname' => 'Firstname',
            'lastname' => 'Lastname',
            'email' => 'Email',
            'password' => 'Password',
            'last_login' => 'Last Login',
        ];
    }
}

controllers/SiteController.php
<?php
namespace app\controllers;

use Yii;
use yii\web\Controller;

//form
use app\models\FormContact;
use app\models\FormRegister;


//tabel
use app\models\Messages;
use app\models\Usersign;
use app\models\JenisProduk;

class SiteController extends Controller
{
    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        //ayam potong
        $ayampotong1 = JenisProduk::find(['kategori'=>'D'])->limit(3)->offset(0)
            ->orderBy(['gambar'=>SORT_DESC])->all();
        $ayampotong2 = JenisProduk::find(['kategori'=>'D'])->limit(3)->offset(3)
            ->orderBy(['gambar'=>SORT_DESC])->all();

        //ayam petelur
        $ayamtelur1 = JenisProduk::find()->where(['kategori'=>'T'])->limit(3)->all();

        return $this->render('index',[
            'ayampotong1'=>$ayampotong1,
            'ayampotong2'=>$ayampotong2,
            'ayamtelur1'=>$ayamtelur1,
        ]);
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new FormContact();
        if($model->load(Yii::$app->request->post())){
            $tabel = new Messages();
            $tabel->date_create = date('Y-m-d H:i:s');
            $tabel->fullname    = $model->fullname;
            $tabel->email       = $model->email;
            $tabel->message     = $model->message;
            
            if($tabel->save()){
                Yii::$app->session->setFlash('success', "Terimakasih sudah memberikan kami kritik dan sarannya.");
                $this->redirect('contact');
            }
        } 
        else {
            return $this->render('contact', ['model'=>$model]);
        }
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Displays register page.
     *
     * @return string
     */
    public function actionRegister()
    {
        $model = new FormRegister();
        if($model->load(Yii::$app->request->post())){
            $tabel = new Usersign();
            $tabel->date_create = date('Y-m-d H:i:s');
            $tabel->firstname   = $model->firstname;
            $tabel->lastname    = $model->lastname;
            $tabel->email       = $model->email;
            $tabel->password    = $model->password;
            
            if($tabel->save()){
                Yii::$app->session->setFlash('success', "Rergister anda berhasil, silahkan langsung login.");
                $this->redirect('register');
            }
        } 
        else {
            return $this->render('register', ['model'=>$model]);
        }
    }

    /**
     * Displays login page.
     *
     * @return string
     */
    public function actionLogin()
    {
        return $this->render('login');
    }

    /**
     * Displays faqs page.
     *
     * @return string
     */
    public function actionFaqs()
    {
        return $this->render('faqs');
    }

    public function actionMycart()
    {
        return $this->render('mycart');
    }

    public function actionAyampotong()
    {
        return $this->render('ayampotong');
    }

    public function actionAyampetelur()
    {
        return $this->render('ayampetelur');
    }

    public function actionAyammasakan()
    {
        return $this->render('ayammasakan');
    }

    public function actionProduct()
    {
        $dataMenu1 = JenisProduk::find()->where(['kategori'=>'D'])->orderBy(['gambar'=>SORT_DESC])->all();
        $dataMenu2 = JenisProduk::find()->where(['kategori'=>'T'])->orderBy(['gambar'=>SORT_DESC])->all();

        $dataproduk1 = JenisProduk::find()->where(['kategori'=>'D'])->orWhere(['kategori'=>'T'])
            ->orderBy(['gambar'=>SORT_DESC])->limit(3)->offset(0)->all();

        $dataproduk2 = JenisProduk::find()->where(['kategori'=>'D'])->orWhere(['kategori'=>'T'])
            ->orderBy(['gambar'=>SORT_DESC])->limit(3)->offset(3)->all();
        
        return $this->render('product', [
            'dataproduk1'=>$dataproduk1,
            'dataproduk2'=>$dataproduk2,
            'dataMenu1'=>$dataMenu1,
            'dataMenu2'=>$dataMenu2,
        ]);
    }

    public function actionDetailproduk($id)
    {
        $dataproduk = JenisProduk::find()->where(['kategori'=>'D'])->orWhere(['kategori'=>'T'])
            ->orderBy(['gambar'=>SORT_DESC])->limit(4)->offset(0)->all();
        
        $detailproduk = JenisProduk::find()->where(['idjenisproduk'=>$id])->one();   

        return $this->render('detailproduk', [
            'dataproduk'=>$dataproduk,
            'detailproduk'=>$detailproduk
        ]);
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>

<!-- breadcrumbs -->
	<div class="breadcrumbs">
		<div class="container">
			<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
				<li><a href="index.html"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
				<li class="active">About</li>
			</ol>
		</div>
	</div>
<!-- //breadcrumbs -->
<!-- about -->
	<div class="about">
		<div class="container">
			<h3 class="w3_agile_header">About Us</h3>
			<div class="about-agileinfo w3layouts">
				<div class="col-md-8 about-wthree-grids grid-top">
					<h4>Warung Bejan</h4>
					<p class="top">Warung bejan merupakan sebuah tempat belanja yang menjual berbagai macam jenis ayam potong dan ayam petelur.
					Warung bejan menjual jenis ayam potong berupa paha, sayap, dada, kepala, ceker ayam, usus dan hati ayam. Selain itu,
					warung bejan juga menjual telur ayam dan ayam afkir (ayam yang sudah tidak dapat bertelur). Harga yang dijual pada Warung
					Bejan sangat terjangkau dan murah meriah. Pembelian bisa dipesan melalui online. Pengiriman hanya dilakukan via gojek
					dan menerima pembelian secara langsung pada Warung Bejan yang terletak di daerah Kutisari.</p>	
					<div class="about-w3agilerow">
						<div class="col-md-4 about-w3imgs">
							<img src="<?php echo Yii::getAlias('@web');?>/tema/images/ayam/pot3.jpg" alt="" class="img-responsive" />
						</div>
						<div class="col-md-4 about-w3imgs">
							<img src="<?php echo Yii::getAlias('@web');?>/tema/images/ayam/pet1.jpg" alt="" class="img-responsive" />
						</div>
						<div class="col-md-4 about-w3imgs">
							<img src="<?php echo Yii::getAlias('@web');?>/tema/images/ayam/pot11.jpg" alt="" class="img-responsive" />
						</div>
						<div class="clearfix"> </div>
					</div>
				</div>
				<div class="col-md-4 about-wthree-grids">
					<div class="offic-time">
						<div class="time-top">
							<h4>Alamat :</h4>
						</div>
						<div class="time-bottom">
							<p>Jl Kutisari Selatan Gg IV a no.26 </p>
							<p>Tenggilis Mejoyo</p>
							<p>Surabaya</p>
							
						</div>
					</div>
					<div class="testi">
						<h3 class="w3_agile_header">Testimonial</h3>
						<!--//End-slider-script -->
						<script src="js/responsiveslides.min.js"></script>
						 <script>
							// You can also use "$(window).load(function() {"
							$(function () {
							  // Slideshow 5
							  $("#slider5").responsiveSlides({
								auto: true,
								pager: false,
								nav: true,
								speed: 500,
								namespace: "callbacks",
								before: function () {
								  $('.events').append("<li>before event fired.</li>");
								},
								after: function () {
								  $('.events').append("<li>after event fired.</li>");
								}
							  });
						
							});
						  </script>
						<div  id="top" class="callbacks_container">
							<ul class="rslides" id="slider5">
								<li>
									<div class="testi-slider">
										<h4>"MAKANAN YANG DIJUAL SANGAT LEZAT .</h4>
										<p>Ayam kremesnya mantab sekali, saya sangat suka yang ada mozarellanya.</p>
										<div class="testi-subscript">
											<p><a href="#">linameritha84@gmail.com,</a>Lina Meritha</p>
											<span class="w3-agilesub"> </span>
										</div>	
									</div>
								</li>
								<li>
									<div class="testi-slider">
										<h4>"MAKANAN YANG DIJUAL SANGAT LEZAT .</h4>
										<p>Ayam kremesnya mantab sekali, saya sangat suka yang ada mozarellanya.</p>
										<div class="testi-subscript">
											<p><a href="#">linameritha84@gmail.com,</a>Lina Meritha</p>
											<span class="w3-agilesub"> </span>
										</div>	
									</div>
								</li>
								<li>
									<div class="testi-slider">
										<h4>"MAKANAN YANG DIJUAL SANGAT LEZAT .</h4>
										<p>Ayam kremesnya mantab sekali, saya sangat suka yang ada mozarellanya.</p>
										<div class="testi-subscript">
											<p><a href="#">linameritha84@gmail.com,</a>Lina Meritha</p>
											<span class="w3-agilesub"> </span>
										</div>	
									</div>
								</li>
							</ul>	
						</div>
					</div>
				</div>	
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- //about -->
	<!-- about-slid -->
	<div class="about-slid agileits-w3layouts"> 
		<div class="container">
			<div class="about-slid-info"> 
				<h2>Warung Bejan</h2>
				<p>Warung Bejan menjual banyak sekali makanan lezat yang higienis dan halal. Warung Bejan berada di seluruh dunia dan selalu ada di hati anda semua. </p>
			</div>
		</div>
	</div>
	<!-- //about-slid -->
	<!-- about-team -->
	<div class="about-team"> 
		<div class="container">
			<h3 class="w3_agile_header">Meet Our Team</h3>
			<div class="team-agileitsinfo">
				<div class="col-md-3 about-team-grids">
					<img src="<?php echo Yii::getAlias('@web');?>/tema/images/Ardi.png" alt="" class="img-responsive" />
					<div class="team-w3lstext">
						<h4><span>ARDIANSYAH,</span> Developer</h4>
						<p>Lahir di Kota Lumajang, tanggal 17 Januari 2017.</p>
					</div>
					<div class="social-icons caption"> 
						<ul>
							<li><a href="#" class="fa fa-facebook facebook"> </a></li>
							<li><a href="#" class="fa fa-twitter twitter"> </a></li>
							<li><a href="#" class="fa fa-google-plus googleplus"> </a></li> 
						</ul>
						<div class="clearfix"> </div>  
					</div>
				</div>
				<div class=" col-md-3 about-team-grids">
					<img src="<?php echo Yii::getAlias('@web');?>/tema/images/Arif.png" alt="" class="img-responsive" />
					<div class="team-w3lstext">
						<h4><span>ARIF RAHMAN S.,</span> Database Administration</h4>
						<p>Pemain sepak bola, pecinta olahraga futsal. Nama Panggilan Cahyok</p>
					</div>
					<div class="social-icons caption"> 
						<ul>
							<li><a href="#" class="fa fa-facebook facebook"> </a></li>
							<li><a href="#" class="fa fa-twitter twitter"> </a></li>
							<li><a href="#" class="fa fa-google-plus googleplus"> </a></li> 
						</ul>
						<div class="clearfix"> </div>  
					</div>
				</div>
				<div class="col-md-3 about-team-grids">
					<img src="<?php echo Yii::getAlias('@web');?>/tema/images/Lina.png" alt="" class="img-responsive" />
					<div class="team-w3lstext">
						<h4><span>LINA MERITHA,</span> Project Manager</h4>				
						<p>Paling imut dan berbadan kecil. Suka senyum hobby menulis.</p>
					</div>
					<div class="social-icons caption"> 
						<ul>
							<li><a href="https://web.facebook.com/linamrth" class="fa fa-facebook facebook"> </a></li>
							<li><a href="https://twitter.com/linameritha" class="fa fa-twitter twitter"> </a></li>
							<li><a href="https://plus.google.com/discover" class="fa fa-google-plus googleplus"> </a></li> 
						</ul>
						<div class="clearfix"> </div>  
					</div>
				</div>
				<div class="col-md-3 about-team-grids">
					<img src="<?php echo Yii::getAlias('@web');?>/tema/images/Novia.png" alt="" class="img-responsive" />
					<div class="team-w3lstext">
						<h4><span>NOVIA RAHAYU K.,</span> Documentation</h4>
						<p>Suka mengaji, hobby menyanyi. Pejuang hebat.</p>
					</div>
					<div class="social-icons caption"> 
						<ul>
							<li><a href="#" class="fa fa-facebook facebook"> </a></li>
							<li><a href="#" class="fa fa-twitter twitter"> </a></li>
							<li><a href="#" class="fa fa-google-plus googleplus"> </a></li> 
						</ul>
						<div class="clearfix"> </div>  
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- //about-team -->

views/site/ayammasakan.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Masakan Ayam';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/ayampetelur.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Ayam Petelur';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/ayampotong.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Ayam Potong';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Contact';
?>
<div class="breadcrumbs">
	<div class="container">
		<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
			<li><a href="<?php echo Yii::$app->homeUrl;?>"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
			<li class="active">Kontak Kami</li>
		</ol>
	</div>
</div>

<?php if (Yii::$app->session->hasFlash('success')): ?>
	<br>
	<div class="container">	
		<div class="alert alert-success alert-dismissable">
			<button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
			<h4><i class="icon fa fa-check"></i>Saved!</h4>
			<?= Yii::$app->session->getFlash('success') ?>
		</div>
	</div>
<?php endif; ?>

<div class="about">
	<div class="w3_agileits_contact_grids">
		<div class="col-md-6 w3_agileits_contact_grid_left">
			<div class="agile_map">
				<iframe src="https://www.google.co.id/maps/place/Politeknik+Elektronika+Negeri+Surabaya/@-7.2756305,112.791546,17z/data=!4m12!1m6!3m5!1s0x2dd7fa10c738f891:0xecfa2529c4987c53!2sPoliteknik+Elektronika+Negeri+Surabaya!8m2!3d-7.2756358!4d112.7937347!3m4!1s0x2dd7fa10c738f891:0xecfa2529c4987c53!8m2!3d-7.2756358!4d112.7937347?hl=id&hl=id" style="border:0"></iframe>
			</div>
			<div class="agileits_w3layouts_map_pos">
				<div class="agileits_w3layouts_map_pos1">
					<h3>Kontak Info</h3>
					<p>Warung Bejan</p>
					<p>Jl. Raya ITS Sukolilo, Surabaya</p>
					<ul class="wthree_contact_info_address">
						<li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:info@example.com">admin@promoayam.com</a></li>
						<li><i class="fa fa-phone" aria-hidden="true"></i>+(62) 8233 4093 822</li>
					</ul>
					<div class="w3_agile_social_icons w3_agile_social_icons_contact">
						<ul>
							<li><a href="#" class="icon icon-cube agile_facebook"></a></li>
							<li><a href="#" class="icon icon-cube agile_rss"></a></li>
							<li><a href="#" class="icon icon-cube agile_t"></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6 w3_agileits_contact_grid_right">
			<h2 class="w3_agile_header">Kirimkan Pesan <span> Anda Ke Kami</span></h2>

			<?php $form = ActiveForm::begin();?>
				<?php echo $form->field($model, 'fullname')->label('Full Name');?>
				<?php echo $form->field($model, 'email')->label('Email');?>
				<?php echo $form->field($model, 'message')->textArea(['rows'=>'3','style'=>'margin: 0px']);?>
				<?= Html::submitButton('Submit', ['class'=>'btn btn-success']); ?>
			<?php ActiveForm::end();?>
		</div>
		<div class="clearfix"> </div>
	</div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/faqs.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'FAQ\'s';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<!-- breadcrumbs -->
<div class="breadcrumbs">
	<div class="container">
		<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
			<li><a href="<?php echo Yii::$app->homeUrl;?>"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
			<li class="active">Login Page</li>
		</ol>
	</div>
</div>
<!-- //breadcrumbs -->
<!-- login -->
<div class="login">
	<div class="container">
		<h2>Login Form</h2>
	
		<div class="login-form-grids animated wow slideInUp" data-wow-delay=".5s">
			<form>
				<input type="email" placeholder="Email Address" required=" " >
				<input type="password" placeholder="Password" required=" " >
				<div class="forgot">
					<a href="#">Forgot Password?</a>
				</div>
				<input type="submit" value="Login">
			</form>
		</div>
		<h4>For New People</h4>
		<p><?php echo Html::a('Register Here', ['site/register']);?> (Or) go back to <a href="<?php echo Yii::$app->homeUrl;?>">Home<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span></a></p>
	</div>
</div>
<!-- end login -->

views/site/mycart.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'My Cart';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/register.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Register';
$this->params['breadcrumbs'][] = $this->title;
?>
<!-- breadcrumbs -->
<div class="breadcrumbs">
	<div class="container">
		<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
			<li><a href="index.html"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
			<li class="active">Register Page</li>
		</ol>
	</div>
</div>
<!-- //breadcrumbs -->
<?php if (Yii::$app->session->hasFlash('success')): ?>
	<br>
	<div class="container">	
		<div class="alert alert-success alert-dismissable">
			<button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
			<h4><i class="icon fa fa-check"></i>Saved!</h4>
			<?= Yii::$app->session->getFlash('success') ?>
		</div>
	</div>
<?php endif; ?>

<!-- register -->
<div class="register">
	<div class="container">
		<h2>Register Here</h2>
		<div class="login-form-grids">
			<h5>profile information</h5>
			<?php $form = ActiveForm::begin();?>
				<?php echo $form->field($model, 'firstname');?>
				<?php echo $form->field($model, 'lastname');?>
				
				<div class="register-check-box">
					<div class="check">
						<label class="checkbox"><input type="checkbox" name="checkbox"><i> </i>Subscribe to Newsletter</label>
					</div>
				</div>

				<h6>Login information</h6>
				<?php echo $form->field($model, 'email');?>
				<?php echo $form->field($model, 'password');?>
				<div class="register-check-box">
					<div class="check">
						<label class="checkbox"><input type="checkbox" name="checkbox"><i> </i>I accept the terms and conditions</label>
					</div>
				</div>
				<input type="submit" value="Register">
			<?php ActiveForm::end();?>
		</div>
		<div class="register-home">
			<a href="<?php echo Yii::$app->homeUrl;?>">Home</a>
		</div>
	</div>
</div>
<!-- //register -->